import 'package:flutter/material.dart';

const List<IconData> categoryIconOptions = [
  Icons.restaurant,
  Icons.coffee,
  Icons.checkroom,
  Icons.shopping_cart,
  Icons.shopping_bag,
  Icons.directions_car,
  Icons.directions_bus,
  Icons.local_gas_station,
  Icons.home,
  Icons.water_drop,
  Icons.electric_bolt,
  Icons.flight,
  Icons.cleaning_services,
  Icons.child_care,
  Icons.pets,
  Icons.local_hospital,
  Icons.movie,
  Icons.theater_comedy,
  Icons.music_note,
  Icons.book,
  Icons.card_giftcard,
  Icons.stars,
  Icons.school,
  Icons.fitness_center,
  Icons.work,
  Icons.trending_up,
  Icons.savings,
  Icons.phone_android,
  Icons.computer,
  Icons.more_horiz,
];
