"""init

Revision ID: f7d03582e8a0
Revises:
Create Date: 2026-03-18 00:28:33.392713+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7d03582e8a0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "oauth_provider",
            sa.Enum("GOOGLE", name="oauthprovider", native_enum=False),
            nullable=False,
        ),
        sa.Column("oauth_sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oauth_provider", "oauth_sub"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_oauth_provider"), "user", ["oauth_provider"], unique=False
    )
    op.create_index(op.f("ix_user_oauth_sub"), "user", ["oauth_sub"], unique=False)
    op.create_table(
        "account",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("sub_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("initial_balance", sa.Float(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),
    )
    op.create_index(
        op.f("ix_account_updated_at"), "account", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_account_user_id_server_updated_at",
        "account",
        ["user_id", "server_updated_at"],
        unique=False,
    )
    op.create_table(
        "achievement",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("unlocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("progress_period", sa.String(length=64), nullable=True),
        sa.Column("is_notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "server_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),
    )
    op.create_index(
        op.f("ix_achievement_updated_at"), "achievement", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_achievement_user_id_server_updated_at",
        "achievement",
        ["user_id", "server_updated_at"],
        unique=False,
    )
    op.create_table(
        "entry",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("debit_account_id", sa.String(length=36), nullable=False),
        sa.Column("credit_account_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),
    )
    op.create_index(op.f("ix_entry_updated_at"), "entry", ["updated_at"], unique=False)
    op.create_index(
        "ix_entry_user_id_server_updated_at",
        "entry",
        ["user_id", "server_updated_at"],
        unique=False,
    )
    op.create_table(
        "entry_tag",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "entry_id", "tag_id"),
    )
    op.create_index(
        op.f("ix_entry_tag_updated_at"), "entry_tag", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_entry_tag_user_id_server_updated_at",
        "entry_tag",
        ["user_id", "server_updated_at"],
        unique=False,
    )
    op.create_table(
        "tag",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),
        sa.UniqueConstraint("user_id", "title", "deleted_at"),
    )
    op.create_index(op.f("ix_tag_updated_at"), "tag", ["updated_at"], unique=False)
    op.create_index(
        "ix_tag_user_id_server_updated_at",
        "tag",
        ["user_id", "server_updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tag_user_id_server_updated_at", table_name="tag")
    op.drop_index(op.f("ix_tag_updated_at"), table_name="tag")
    op.drop_table("tag")
    op.drop_index("ix_entry_tag_user_id_server_updated_at", table_name="entry_tag")
    op.drop_index(op.f("ix_entry_tag_updated_at"), table_name="entry_tag")
    op.drop_table("entry_tag")
    op.drop_index("ix_entry_user_id_server_updated_at", table_name="entry")
    op.drop_index(op.f("ix_entry_updated_at"), table_name="entry")
    op.drop_table("entry")
    op.drop_index("ix_achievement_user_id_server_updated_at", table_name="achievement")
    op.drop_index(op.f("ix_achievement_updated_at"), table_name="achievement")
    op.drop_table("achievement")
    op.drop_index("ix_account_user_id_server_updated_at", table_name="account")
    op.drop_index(op.f("ix_account_updated_at"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_user_oauth_sub"), table_name="user")
    op.drop_index(op.f("ix_user_oauth_provider"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
