"""remove_unique_constraints

Revision ID: 7d1244cb8b45
Revises: c8f4e2b91a3d
Create Date: 2026-06-14 09:42:15.227098+00:00

"""

from collections.abc import Sequence

from alembic import op

revision: str = "7d1244cb8b45"
down_revision: str | Sequence[str] | None = "c8f4e2b91a3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("budget_user_id_year_month_key"), "budget", type_="unique")
    op.drop_constraint(
        op.f("category_budget_user_id_year_month_account_id_key"),
        "category_budget",
        type_="unique",
    )
    op.drop_constraint(op.f("tag_user_id_title_deleted_at_key"), "tag", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("tag_user_id_title_deleted_at_key"),
        "tag",
        ["user_id", "title", "deleted_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("category_budget_user_id_year_month_account_id_key"),
        "category_budget",
        ["user_id", "year", "month", "account_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("budget_user_id_year_month_key"),
        "budget",
        ["user_id", "year", "month"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
